name: in_app_file_view
description: "A Flutter plugin to view various file types such as PDFs, DOCs, PPTs, and Excel files."
version: 0.0.3
repository: "https://github.com/harshrastogi-1/in_app_file_view_flutter"
license: "MIT"

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      #      android:
      #        package: com.file.view
      #        pluginClass: FlutterInAppFileViewPlugin
      ios:
        pluginClass: InAppFileViewPlugin
      # -------------------
#      some_platform:
#        pluginClass: somePluginClass
    # -------------------
